name: 'Prepare: Source, Python, Poetry'
description: 'Prerequisites for almost all jobs'

runs:
  using: "composite"
  steps:
    - name: Prepare Python
      id: prepare-python
      uses: ./.github/actions/python

    - name: Prepare Poetry
      uses: ./.github/actions/poetry
      with:
        python-version: ${{ steps.prepare-python.outputs.python-version }}
