name: 'Prepare Python 3.10'
description: 'Install Python'

outputs:
  python-version:
    description: "Python version"
    value: ${{ steps.install-python.outputs.python-version }}

runs:
  using: "composite"
  steps:
    - name: Install Python
      id: install-python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
